### ISSUE TITLE
add reasons for rewrite

### ISSUE THREAD

**Issue by kkweon** [OMSCentral/omscentral-react#3]
Why is it being rewritten again? Just for fun 😄? 
What are you trying to achieve with this rewrite? 
Can you please add to README also?

**Comment by sw-yx** [comment]
i dont like angular :)

**Comment by martzcodes** [comment]
Closing... this isn't an actual issue

**Comment by kkweon** [comment]
This is an issue. Please update README this and the original README. 

In this repo README, please update it is rewritten.

In the original repo's README, ask people to contribute to this rather than the old.

Otherwise, it is very confusing. Right know it sounds like the original repo will die away and it is not worth sending a new feature update.

**Comment by martzcodes** [comment]
Archived the old one and pointed it to here
