### ISSUE TITLE
floating header while scrolling (issue migrated from old omscentral)

### ISSUE THREAD

**Issue by brij1234** [OMSCentral/omscentral-react#4]
The title says it all. It's a slight inconvenience to scroll up to remember which column I'm looking at.

[A potential solution](https://stackoverflow.com/a/52008347/4234321)

**Comment by sw-yx** [comment]
yep, easy

**Comment by sw-yx** [comment]
![materialtable](https://user-images.githubusercontent.com/6764957/64915941-d7ce2180-d740-11e9-9976-deb0d121cafd.gif)

oneliner in the component we use
