### ISSUE TITLE
Unable to sign in with google/twitter/github or facebook

### ISSUE THREAD

**Issue by joshuakaluba** [OMSCentral/omscentral-react#7]
I tried to sign in using https://omscentral.netlify.com/ and also https://deploy-preview-6--omscentral.netlify.com/ but was presented with the following error.

![image](https://user-images.githubusercontent.com/15926804/63805676-f7afb980-c8e7-11e9-92b4-ac1f6257525b.png)

**Comment by sw-yx** [comment]
acknowledged! its not yet ready for use tbh

**Comment by sw-yx** [comment]
this should be fixed thanks to matt whitelisting us
