### ISSUE TITLE
Display issue on chrome

### ISSUE THREAD

**Issue by titoesteves** [OMSCentral/omscentral-react#8]
When viewing certain courses in chrome, the text from paragraph tags are cut off on the right hand side. This seems to be an issue specific to chrome as firefox displays just fine. 

Chrome version: Version 76.0.3809.87 (Official Build) (64-bit)
Example course: https://omscentral.com/courses/CSE-6242
Screenshot: ![](https://i.imgur.com/e3Rl2RF.png)

**Comment by sw-yx** [comment]
thanks, i will address this!

**Comment by sw-yx** [comment]
hang on.. this isn't the new version. you're on the wrong repo. this is the React version.


https://omscentral.netlify.com/courses/CSE-6242

![image](https://user-images.githubusercontent.com/6764957/64915960-5b880e00-d741-11e9-9c95-fec9acd3df79.png)

**Comment by titoesteves** [comment]
I was unaware there was a new version. I just tried to access the new site and receive an error when trying to sign
![](https://i.imgur.com/FlH9NzQ.png)

Also, why are you forcing students to sign in?

**Comment by sw-yx** [comment]
honestly it was just easier to code for an mvp. i’ll take a pr to move the auth lower down
